spring:
  application:
    name: accountservice
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    url: jdbc:mysql://localhost:3306/accountdb
    enabled: true
    user: root
    password: rootpassword
    change-log: classpath:db/changelog/changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    acks: 1

server:
  port: 9215